### ISSUE TITLE
jmeter-slave pod requested too many cpu and memory.

### ISSUE THREAD

**Issue by mugioka** [Rbillon59/jmeter-k8s-starterkit#16]
Hi, this tool is very nice.
However, the jmeter-slave pods that this tool creates seem to require a lot of CPU and memory. So even if I create a lot of pods, they will not run.
So I think it would be better to reduce the cpu and memory requested, what do you think?

**Comment by mugioka** [comment]
https://github.com/Rbillon59/jmeter-k8s-starterkit/blob/master/k8s/jmeter/jmeter-slave.yaml#L85-L88

How about changing the above requests to the following?

````
resources:
    requests:
            memory: "512Mi".
            cpu: "512m"
```
